[workspace]
authors = ["jpils <pilsj00@gmail.com>"]
channels = ["conda-forge"]
name = "alchemist"
platforms = ["linux-64"]
version = "0.1.0"

[feature.common.dependencies]
python = ">=3.14,<3.15"
numpy = "*"

[feature.common.pypi-dependencies]
ase = "*"

[feature.upet.pypi-dependencies]
upet = ">=0.2.6,<0.3"

# We'll fill this in once we know exactly how we're using n2p2.
[feature.n2p2.pypi-dependencies]

[environments]
upet = ["common", "upet"]
n2p2 = ["common", "n2p2"]
