import os
import ase.io


def export_extxyz(
    project_dir,
    generation_num,
    train_set,
    validation_set,
    test_set,
):
    """
    Write UPET extxyz datasets.
    """

    target_dir = os.path.join(
        project_dir,
        "training",
        f"generation_{generation_num}",
        "dataset",
    )

    os.makedirs(
        target_dir,
        exist_ok=True,
    )

    train_path = os.path.join(
        target_dir,
        "train.extxyz",
    )

    validation_path = os.path.join(
        target_dir,
        "validation.extxyz",
    )

    test_path = os.path.join(
        target_dir,
        "test.extxyz",
    )

    ase.io.write(
        train_path,
        train_set,
        format="extxyz",
    )

    if validation_set:
        ase.io.write(
            validation_path,
            validation_set,
            format="extxyz",
        )

    if test_set:
        ase.io.write(
            test_path,
            test_set,
            format="extxyz",
        )

    print(
        f"[+] Dataset exported successfully: {target_dir}/"
    )

    print(
        f"    - train.extxyz      : {len(train_set)} frames"
    )

    print(
        f"    - validation.extxyz : {len(validation_set)} frames"
    )

    print(
        f"    - test.extxyz       : {len(test_set)} frames"
    )

def write_runner_structure(file, atoms):
    """
    Write a single ASE Atoms object in n2p2 Runner format.
    """

    file.write("begin\n")

    file.write("comment generated by ai_scheduler\n")

    for lattice_vector in atoms.cell:
        file.write(
            f"lattice "
            f"{lattice_vector[0]:.9f} "
            f"{lattice_vector[1]:.9f} "
            f"{lattice_vector[2]:.9f}\n"
        )
    
    symbols = atoms.get_chemical_symbols()
    forces = atoms.get_forces()

    for position, symbol, force in zip(
        atoms.positions,
        atoms.get_chemical_symbols(),
        atoms.get_forces(),
    ):
        file.write(
            f"atom "
            f"{position[0]:.5f} "
            f"{position[1]:.5f} "
            f"{position[2]:.5f} "
            f"{symbol} "
            f"0.0 0.0 "
            f"{force[0]:.6f} "
            f"{force[1]:.6f} "
            f"{force[2]:.6f}\n"
        )
    
    energy = atoms.get_potential_energy()

    file.write(f"energy {atoms.get_potential_energy():.6f}\n")
    file.write("charge 0.0\n")
    file.write("end\n")

def export_runner(
    project_dir,
    generation_num,
    dataset,
):
    """
    Write an n2p2 Runner input.data file.
    """

    target_dir = os.path.join(
        project_dir,
        "training",
        f"generation_{generation_num}",
        "dataset",
    )

    os.makedirs(
        target_dir,
        exist_ok=True,
    )

    output_file = os.path.join(
        target_dir,
        "input.data",
    )

    with open(
        output_file,
        "w",
        encoding="utf-8",
    ) as file:
        for atoms in dataset:
            write_runner_structure(
                file,
                atoms,
            )

    print(
        f"[+] Runner dataset exported successfully: "
        f"{output_file}"
    )

    print(
        f"    - structures : {len(dataset)}"
    )